on: [push, pull_request]
name: Test & Build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29
    - name: Install Rakyll's gotest utility
      run: go install github.com/rakyll/gotest
    - name: Run golint-ci
      run: make golint
    - name: Test
      run: make test
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build binary for linux
      if: matrix.os == 'ubuntu-latest'
      run: make linux
    - name: Build binary for macos
      if: matrix.os == 'macos-latest'
      run: make darwin
    - name: Build binary for windows
      if: matrix.os == 'windows-latest'
      run: make window
        